Dereferenced symlinked videodev files, was useful at one time but now just a nuisance.

diff --git a/rte/mp1e/configure.in b/rte/mp1e/configure.in
--- a/rte/mp1e/configure.in
+++ b/rte/mp1e/configure.in
@@ -1,18 +1,21 @@
 dnl Process this file with autoconf to produce a configure script.
 
-AC_REVISION($Id: configure.in,v 1.18 2002-06-12 03:59:06 mschimek Exp $)
+AC_REVISION($Id: configure.in,v 1.19 2002-06-18 02:22:23 mschimek Exp $)
 
 AC_INIT(configure.in)
 AM_INIT_AUTOMAKE(mp1e, 1.9.3)
 AM_CONFIG_HEADER(config.h)
 AM_ACLOCAL_INCLUDE(macros)
 
-test "x`echo $CFLAGS | grep -e -g`" != "x" && CFLAGS="$CFLAGS -O0"
+test -n "`echo $CFLAGS | grep -e -g`" && CFLAGS="$CFLAGS -O0"
 dnl -fomit is neccessary to free enough regs for some inline asm
 CFLAGS="-O2 -fomit-frame-pointer $CFLAGS"
 
 AC_PROG_CC
 AM_PROG_AS
+
+dnl fixme
+rm config.status
 
 dnl libtool is used to build a shared lib mp1e backend for rte.
 dnl command line mp1e needs only the static libs for linking
@@ -20,9 +23,10 @@ dnl which saves compile time.
 AC_DISABLE_SHARED
 AC_PROG_LIBTOOL
 
-AM_CONDITIONAL(BACKEND_MP1E, test 0=1)
+AM_CONDITIONAL(BACKEND_MP1E, ! test 0)
 
-test -e site_def.h || cat <<EOF >site_def.h
+dnl XXX should be builddir
+test -e $srcdir/site_def.h || cat <<EOF >$srcdir/site_def.h
 /* Site specific definitions */
 
 #ifndef SITE_DEF_H
@@ -32,19 +36,17 @@ EOF
 
 create_links () {
 	for i in $3; do
-		test -e $2/$i || {
-			test -f $1/$i || {
-				echo "$1/$i not found, abort."
+		test -e $srcdir/$2/$i || {
+			test -f $srcdir/$1/$i || {
+				echo "$srcdir/$1/$i not found, abort."
 				exit 1
 			}
-			echo "creating link for" $2/$i
+			echo "creating link for" $srcdir/$2/$i
 			dnl absolute path because make dist moves the tree
-			ln -s `cd $1; pwd; cd - >/dev/null`/$i $2/$i || exit 1
+			ln -s `cd $srcdir/$1; pwd; cd - >/dev/null`/$i $srcdir/$2/$i || exit 1
 		}
 	done
 }
-
-create_links ../common common "list.h fifo.h threads.h"
 
 dnl mp1e standalone distr cuts rte off, hence
 create_links ../src . "context.h codec.h rte.h option.h rtepriv.h"
@@ -152,9 +154,17 @@ systems/Makefile
 common/Makefile
 devices/Makefile
 test/Makefile
+macros/Makefile
 mp1e.lsm
 mp1e.spec
 ])
+
+for var in bindir mandir; do
+  eval t=$`echo $var`
+  dnl recursive expansion
+  while test -n "`echo $t | grep \\\\$`"; do eval t=$t; done
+  eval `echo $var`_rx=$t
+done
 
 echo "
 	Mp1e frontend driver interfaces
@@ -165,4 +175,7 @@ echo "
 	Advanced Linux Sound Architecture	$have_libasound
 	Enlightened Sound Daemon		$have_esd
 	SGI Audio File Library			$have_audiofile
+
+        Files install in                        $bindir_rx
+                                                $mandir_rx
 "
