Dereferenced symlinked videodev files, was useful at one time but now just a nuisance.

diff --git a/rte/mp1e/configure.in b/rte/mp1e/configure.in
--- a/rte/mp1e/configure.in
+++ b/rte/mp1e/configure.in
@@ -1,32 +1,36 @@
 dnl Process this file with autoconf to produce a configure script.
-
-AC_REVISION($Id: configure.in,v 1.19 2002-06-18 02:22:23 mschimek Exp $)
+AC_REVISION($Id: configure.in,v 1.20 2002-06-24 03:19:05 mschimek Exp $)
 
 AC_INIT(configure.in)
-AM_INIT_AUTOMAKE(mp1e, 1.9.3)
+AM_INIT_AUTOMAKE(mp1e, 1.9.3cvs)
 AM_CONFIG_HEADER(config.h)
 AM_ACLOCAL_INCLUDE(macros)
 
-test -n "`echo $CFLAGS | grep -e -g`" && CFLAGS="$CFLAGS -O0"
-dnl -fomit is neccessary to free enough regs for some inline asm
-CFLAGS="-O2 -fomit-frame-pointer $CFLAGS"
+dnl
+dnl Default to -O2, except we are debugging -g. -fomit-frame-pointer
+dnl is neccessary to free enough regs for some inline asm.
+dnl
+test -z "`echo $CFLAGS | grep -e -g`" && CFLAGS="-O2 $CFLAGS"
+CFLAGS="-fomit-frame-pointer $CFLAGS"
 
 AC_PROG_CC
 AM_PROG_AS
 
-dnl fixme
-rm config.status
-
+dnl
 dnl libtool is used to build a shared lib mp1e backend for rte.
-dnl command line mp1e needs only the static libs for linking
+dnl Command line mp1e needs only the static libs for linking
 dnl which saves compile time.
+dnl
 AC_DISABLE_SHARED
 AC_PROG_LIBTOOL
 
 AM_CONDITIONAL(BACKEND_MP1E, ! test 0)
 
-dnl XXX should be builddir
-test -e $srcdir/site_def.h || cat <<EOF >$srcdir/site_def.h
+dnl
+dnl NB this is created in builddir, not srcdir.
+dnl Configure will add -I builddir as necessary.
+dnl
+test -e site_def.h || cat <<EOF >site_def.h
 /* Site specific definitions */
 
 #ifndef SITE_DEF_H
@@ -34,22 +38,30 @@ test -e $srcdir/site_def.h || cat <<EOF >$srcdir/site_def.h
 #endif /* SITE_DEF_H */
 EOF
 
-create_links () {
-	for i in $3; do
-		test -e $srcdir/$2/$i || {
-			test -f $srcdir/$1/$i || {
-				echo "$srcdir/$1/$i not found, abort."
-				exit 1
-			}
-			echo "creating link for" $srcdir/$2/$i
-			dnl absolute path because make dist moves the tree
-			ln -s `cd $srcdir/$1; pwd; cd - >/dev/null`/$i $srcdir/$2/$i || exit 1
-		}
-	done
+dnl
+dnl When mp1e is configured as rte backend we use rtepriv.h directly
+dnl (-I rte/src). As standalone we have a copy of the rte headers
+dnl in rte/. (Created only when configuring the cvs source as standalone
+dnl mp1e. The rte and mp1e dist have everything in place already.)
+dnl
+test -e $srcdir/b_mp1e.c && {
+  cd $srcdir
+  test -e rte || mkdir rte || exit 1
+  for file in context.h codec.h rte.h option.h rtepriv.h; do
+    abs_file=`cd ../src; pwd; cd - >/dev/null`/$file
+    test -f $abs_file || {
+      echo "No rte source at $abs_file, abort."
+      exit 1
+    }
+    echo "creating link" $abs_file "->" rte/$file
+    dnl absolute path because make dist moves the tree
+    test -e rte/$file || ln -s $abs_file rte/$file || exit 1
+  done
+  cd -
 }
 
-dnl mp1e standalone distr cuts rte off, hence
-create_links ../src . "context.h codec.h rte.h option.h rtepriv.h"
+RTE_CFLAGS=-I`cd $srcdir; pwd`/rte
+AC_SUBST(RTE_CFLAGS)
 
 AC_CHECK_FUNCS(memalign)
 AC_CHECK_FUNCS(program_invocation_name)
@@ -63,8 +75,8 @@ dnl
 use_sse2=no
 AC_MSG_CHECKING([whether as supports SSE2])
 AC_TRY_COMPILE(, __asm__ __volatile__ (" movdqu 0,%xmm0\n"),
-	[AC_DEFINE(USE_SSE2, 1, [Define if 'as' supports SSE2])
-	 use_sse2=yes])
+  [AC_DEFINE(USE_SSE2, 1, [Define if 'as' supports SSE2])
+    use_sse2=yes])
 AC_MSG_RESULT($use_sse2)
 AM_CONDITIONAL(USE_SSE2, test x$use_sse2 = xyes)
 
@@ -72,56 +84,6 @@ dnl
 dnl MMX emulator for testing purposes
 dnl
 AC_CHECK_LIB(mmxemu, mmxemu_configure)
-
-dnl ---------------------------------------------------------------------------
-dnl Driver interfaces
-dnl ---------------------------------------------------------------------------
-
-dnl
-dnl OSS support
-dnl
-have_oss=no
-AC_CHECK_HEADER(sys/soundcard.h,
-	[have_oss=yes
-	 AC_DEFINE(HAVE_OSS, 1, [Define if the OSS API is available])])
-
-dnl
-dnl ALSA support (libasound)
-dnl
-have_libasound=no
-AM_PATH_ALSA_([0.5.9], have_libasound=yes, true)
-if test "x$have_libasound" = "xyes"; then
-	AC_DEFINE(HAVE_ALSA, 1, [Define if you have ALSA.])
-fi
-
-dnl
-dnl EsounD support
-dnl
-have_esd=no
-AC_MSG_CHECKING(for EsounD)
-ESD_VERSION=`esd-config --version`
-if test $? -eq 0; then
-	AC_MSG_RESULT($ESD_VERSION)
-	ESD_LIBS=`esd-config --libs`
-	ESD_CFLAGS=`esd-config --cflags`
-	AC_SUBST(ESD_CFLAGS)
-	AC_SUBST(ESD_LIBS)
-	have_esd=yes
-	AC_DEFINE(HAVE_ESD, 1, [Define if you have ESD.])
-else
-	AC_MSG_RESULT([not present])
-fi
-
-dnl
-dnl Audio File library (libaudiofile)
-dnl for audio compression from WAV etc
-dnl
-have_audiofile=yes
-AC_CHECK_HEADER(audiofile.h,
-	AC_CHECK_LIB(audiofile, afSetVirtualSampleFormat,,
-		have_audiofile=no), have_audiofile=no)
-
-dnl ---------------------------------------------------------------------------
 
 dnl
 dnl XVideo support (libxv)
@@ -133,30 +95,78 @@ AC_CHECK_LIB(Xv, XvShmPutImage, HAVE_XV="yes",, $X_LIBS -lX11 -lXext)
 dnl
 dnl Test GUI
 dnl
-AC_ARG_ENABLE(test,[  --enable-test           enable test gui])
+AC_ARG_ENABLE(test, AC_HELP_STRING([--enable-test], [enable test gui]))
 if test "$enable_test" = "yes"; then
 if test "$HAVE_XV" = "yes"; then
-	GTK_LIBS="`gtk-config --libs` -lXv -lXext"
-	GTK_CFLAGS=`gtk-config --cflags`
-	AC_SUBST(GTK_CFLAGS)
-	AC_SUBST(GTK_LIBS)
-	AC_DEFINE(TEST_PREVIEW, 1, [Define to compile preview.])
-	AC_DEFINE(HAVE_LIBXV, 1, [Define if you have the XVideo library (-lxv).])
+  GTK_LIBS="`gtk-config --libs` -lXv -lXext"
+  GTK_CFLAGS=`gtk-config --cflags`
+  AC_SUBST(GTK_CFLAGS)
+  AC_SUBST(GTK_LIBS)
+  AC_DEFINE(TEST_PREVIEW, 1, [Define to compile preview.])
+  AC_DEFINE(HAVE_LIBXV, 1, [Define if you have the XVideo library (-lxv).])
 fi
 fi
 
+dnl ---------------------------------------------------------------------------
+dnl Driver interfaces
+dnl ---------------------------------------------------------------------------
+
+dnl
+dnl OSS support
+dnl
+have_oss=no
+AC_CHECK_HEADER(sys/soundcard.h,
+  [have_oss=yes
+    AC_DEFINE(HAVE_OSS, 1, [Define if the OSS API is available])])
+
+dnl
+dnl ALSA support (libasound)
+dnl
+have_libasound=no
+AM_PATH_ALSA_([0.5.9], have_libasound=yes, true)
+if test "x$have_libasound" = "xyes"; then
+  AC_DEFINE(HAVE_ALSA, 1, [Define if you have ALSA.])
+fi
+
+dnl
+dnl EsounD support
+dnl
+have_esd=no
+AC_MSG_CHECKING(for EsounD)
+ESD_VERSION=`esd-config --version`
+if test $? -eq 0; then
+  AC_MSG_RESULT($ESD_VERSION)
+  ESD_LIBS=`esd-config --libs`
+  ESD_CFLAGS=`esd-config --cflags`
+  AC_SUBST(ESD_CFLAGS)
+  AC_SUBST(ESD_LIBS)
+  have_esd=yes
+  AC_DEFINE(HAVE_ESD, 1, [Define if you have ESD.])
+else
+  AC_MSG_RESULT([not present])
+fi
+
+dnl
+dnl Audio File library (libaudiofile)
+dnl for audio compression from WAV etc
+dnl
+have_audiofile=yes
+AC_CHECK_HEADER(audiofile.h,
+  AC_CHECK_LIB(audiofile, afSetVirtualSampleFormat,,
+    have_audiofile=no), have_audiofile=no)
+
 AC_OUTPUT([
-Makefile
-video/Makefile
-audio/Makefile
-vbi/Makefile
-systems/Makefile
-common/Makefile
-devices/Makefile
-test/Makefile
-macros/Makefile
-mp1e.lsm
-mp1e.spec
+  Makefile
+  video/Makefile
+  audio/Makefile
+  vbi/Makefile
+  systems/Makefile
+  common/Makefile
+  devices/Makefile
+  test/Makefile
+  macros/Makefile
+  mp1e.lsm
+  mp1e.spec
 ])
 
 for var in bindir mandir; do
